In [1]:
import pandas as pd
import os
import json
import ast

# converting release_conditions.json file to dataframe

In [2]:
with open("release_conditions.json") as jf:
    data = json.load(jf)

In [3]:
# keys present in the json data
keys = list(data.keys())
print('Dictionary Keys (all conditions): ',keys)
print()
print('Total Number of conditions: ',len(keys))
print()
print('Keys for a condition: ', data[keys[0]].keys())

Dictionary Keys (all conditions):  ['Spontaneous pneumothorax', 'Cluster headache', 'Boerhaave', 'Spontaneous rib fracture', 'GERD', 'HIV (initial infection)', 'Anemia', 'Viral pharyngitis', 'Inguinal hernia', 'Myasthenia gravis', 'Whooping cough', 'Anaphylaxis', 'Epiglottitis', 'Guillain-Barré syndrome', 'Acute laryngitis', 'Croup', 'PSVT', 'Atrial fibrillation', 'Bronchiectasis', 'Allergic sinusitis', 'Chagas', 'Scombroid food poisoning', 'Myocarditis', 'Larygospasm', 'Acute dystonic reactions', 'Localized edema', 'SLE', 'Tuberculosis', 'Unstable angina', 'Stable angina', 'Ebola', 'Acute otitis media', 'Panic attack', 'Bronchospasm / acute asthma exacerbation', 'Bronchitis', 'Acute COPD exacerbation / infection', 'Pulmonary embolism', 'URTI', 'Influenza', 'Pneumonia', 'Acute rhinosinusitis', 'Chronic rhinosinusitis', 'Bronchiolitis', 'Pulmonary neoplasm', 'Possible NSTEMI / STEMI', 'Sarcoidosis', 'Pancreatic neoplasm', 'Acute pulmonary edema', 'Pericarditis']

Total Number of conditions:  49

Keys for a condition:  dict_keys(['condition_name', 'cond-name-fr', 'cond-name-eng', 'icd10-id', 'symptoms', 'antecedents', 'severity'])

In [4]:
df = pd.DataFrame.from_dict(data, orient='index')
df = df.reset_index(drop=True)

In [5]:
# save dataframe as csv
df.to_csv('release_conditions.csv', index=False)

,condition_name,cond-name-fr,cond-name-eng,icd10-id,symptoms,antecedents,severity
0,Spontaneous pneumothorax,Pneumothorax spontané,Spontaneous pneumothorax,J93,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_79': {}, 'E_165': {}, 'E_21': {}, 'E_123':...",2
1,Cluster headache,Céphalée en grappe,Cluster headache,g44.009,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_25': {}, 'E_78': {}, 'E_184': {}, 'E_204':...",3
2,Boerhaave,Syndrome de Boerhaave,Boerhaave,K22.3,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_78': {}, 'E_204': {}}",2
3,Spontaneous rib fracture,Fracture de côte spontanée,Spontaneous rib fracture,S22.9,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_78': {}, 'E_37': {}, 'E_153': {}, 'E_204':...",3
4,GERD,RGO,GERD,K21,"{'E_173': {}, 'E_201': {}, 'E_215': {}, 'E_55'...","{'E_70': {}, 'E_167': {}, 'E_124': {}, 'E_78':...",3
5,HIV (initial infection),VIH (Primo-infection),HIV (initial infection),B20,"{'E_91': {}, 'E_88': {}, 'E_144': {}, 'E_162':...","{'E_115': {}, 'E_61': {}, 'E_27': {}, 'E_189':...",3
6,Anemia,Anémie,Anemia,D64.9,"{'E_76': {}, 'E_89': {}, 'E_88': {}, 'E_66': {...","{'E_7': {}, 'E_24': {}, 'E_26': {}, 'E_167': {...",4
7,Viral pharyngitis,Pharyngite virale,Viral pharyngitis,J02.9,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_49': {}, 'E_48': {}, 'E_79': {}, 'E_41': {...",4
8,Inguinal hernia,Hernie inguinale,Inguinal hernia,K40,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_160': {}, 'E_70': {}, 'E_204': {}}",3
9,Myasthenia gravis,Myasthénie grave,Myasthenia gravis,G70.0,"{'E_65': {}, 'E_63': {}, 'E_52': {}, 'E_172': ...","{'E_28': {}, 'E_204': {}}",3
10,Whooping cough,Coqueluche,Whooping cough,A37,"{'E_166': {}, 'E_203': {}, 'E_112': {}}","{'E_40': {}, 'E_124': {}, 'E_70': {}, 'E_209':...",4
11,Anaphylaxis,Anaphylaxie,Anaphylaxis,T78.0,"{'E_42': {}, 'E_82': {}, 'E_159': {}, 'E_66': ...","{'E_226': {}, 'E_12': {}, 'E_204': {}}",1
12,Epiglottitis,Épiglottite,Epiglottitis,J05.1,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_104': {}, 'E_69': {}, 'E_209': {}, 'E_78':...",2
13,Guillain-Barré syndrome,Syndrome de Guillain-Barré,Guillain-Barré syndrome,G61.0,"{'E_84': {}, 'E_66': {}, 'E_83': {}, 'E_157': ...","{'E_0': {}, 'E_204': {}}",2
14,Acute laryngitis,Laryngite aigue,Acute laryngitis,J04.0,"{'E_212': {}, 'E_91': {}, 'E_201': {}, 'E_55':...","{'E_116': {}, 'E_48': {}, 'E_49': {}, 'E_79': ...",4
15,Croup,Laryngo-trachéo-bronchite (Croup),Croup,J05.0,"{'E_194': {}, 'E_91': {}, 'E_181': {}, 'E_202'...","{'E_4': {}, 'E_209': {}, 'E_204': {}}",2
16,PSVT,TSVP,PSVT,I47.1,"{'E_155': {}, 'E_76': {}, 'E_66': {}, 'E_82': ...","{'E_62': {}, 'E_60': {}, 'E_35': {}, 'E_213': ...",2
17,Atrial fibrillation,Fibrillation auriculaire/Flutter auriculaire,Atrial fibrillation,I48.91,"{'E_155': {}, 'E_66': {}, 'E_76': {}, 'E_218':...","{'E_139': {}, 'E_19': {}, 'E_104': {}, 'E_105'...",3
18,Bronchiectasis,Bronchiectasies,Bronchiectasis,J47,"{'E_201': {}, 'E_77': {}, 'E_45': {}, 'E_66': {}}","{'E_17': {}, 'E_18': {}, 'E_118': {}, 'E_47': ...",3
19,Allergic sinusitis,Rhinite allergique,Allergic sinusitis,J30,"{'E_201': {}, 'E_181': {}, 'E_170': {}, 'E_169...","{'E_226': {}, 'E_207': {}, 'E_86': {}, 'E_87':...",4
20,Chagas,Chagas,Chagas,B57,"{'E_91': {}, 'E_175': {}, 'E_174': {}, 'E_148'...",{'E_204': {}},3
21,Scombroid food poisoning,Scombroïde,Scombroid food poisoning,T61.1,"{'E_82': {}, 'E_133': {}, 'E_129': {}, 'E_130'...","{'E_187': {}, 'E_204': {}}",2
22,Myocarditis,Myocardite,Myocarditis,I51.4,"{'E_175': {}, 'E_155': {}, 'E_66': {}, 'E_55':...","{'E_0': {}, 'E_204': {}}",2
23,Larygospasm,Laryngospasme,Larygospasm,J38.5,{'E_194': {}},"{'E_124': {}, 'E_116': {}, 'E_79': {}, 'E_222'...",1
24,Acute dystonic reactions,Réaction dystonique aïgue,Acute dystonic reactions,G24.02,"{'E_128': {}, 'E_193': {}, 'E_205': {}, 'E_192...","{'E_62': {}, 'E_15': {}, 'E_147': {}, 'E_204':...",2
25,Localized edema,Oedème localisé ou généralisé sans atteinte pu...,Localized edema,R60.0,"{'E_66': {}, 'E_152': {}, 'E_151': {}, 'E_217'...","{'E_137': {}, 'E_158': {}, 'E_109': {}, 'E_149...",4
26,SLE,Lupus érythémateux disséminé (LED),SLE,M34,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_79': {}, 'E_141': {}, 'E_11': {}, 'E_3': {...",4
27,Tuberculosis,Tuberculose,Tuberculosis,a15,"{'E_201': {}, 'E_45': {}, 'E_66': {}, 'E_91': ...","{'E_78': {}, 'E_61': {}, 'E_2': {}, 'E_44': {}...",3
28,Unstable angina,Angine instable,Unstable angina,I20.0,"{'E_218': {}, 'E_13': {}, 'E_14': {}, 'E_55': ...","{'E_69': {}, 'E_104': {}, 'E_79': {}, 'E_70': ...",2
29,Stable angina,Angine stable,Stable angina,I20.9,"{'E_218': {}, 'E_55': {}, 'E_53': {}, 'E_57': ...","{'E_105': {}, 'E_69': {}, 'E_104': {}, 'E_79':...",2
30,Ebola,Ebola,Ebola,a98.4,"{'E_178': {}, 'E_91': {}, 'E_148': {}, 'E_51':...","{'E_41': {}, 'E_204': {}, 'E_73': {}}",1
31,Acute otitis media,Otite moyenne aigue (OMA),Acute otitis media,H66.90,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_1': {}, 'E_209': {}, 'E_204': {}}",4
32,Panic attack,Attaque de panique,Panic attack,f41,"{'E_155': {}, 'E_75': {}, 'E_55': {}, 'E_53': ...","{'E_81': {}, 'E_80': {}, 'E_78': {}, 'E_29': {...",5
33,Bronchospasm / acute asthma exacerbation,Asthme exacerbé ou bronchospasme,Bronchospasm / acute asthma exacerbation,J45,"{'E_201': {}, 'E_66': {}, 'E_214': {}}","{'E_116': {}, 'E_207': {}, 'E_87': {}, 'E_222'...",3
34,Bronchitis,Bronchite,Bronchitis,j40,"{'E_219': {}, 'E_201': {}, 'E_97': {}, 'E_181'...","{'E_209': {}, 'E_79': {}, 'E_123': {}, 'E_204'...",4
35,Acute COPD exacerbation / infection,Exacerbation aigue de MPOC et/ou surinfection ...,Acute COPD exacerbation / infection,j44.1,"{'E_201': {}, 'E_214': {}, 'E_77': {}, 'E_66':...","{'E_125': {}, 'E_79': {}, 'E_123': {}, 'E_72':...",3
36,Pulmonary embolism,Embolie pulmonaire,Pulmonary embolism,i26,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_34': {}, 'E_109': {}, 'E_196': {}, 'E_110'...",2
37,URTI,IVRS ou virémie,URTI,j06.9,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_48': {}, 'E_222': {}, 'E_49': {}, 'E_41': ...",5
38,Influenza,Possible influenza ou syndrome virémique typique,Influenza,j11.1,"{'E_133': {}, 'E_129': {}, 'E_130': {}, 'E_134...","{'E_79': {}, 'E_227': {}, 'E_204': {}}",3
39,Pneumonia,Pneumonie,Pneumonia,"j17, j18","{'E_220': {}, 'E_55': {}, 'E_53': {}, 'E_57': ...","{'E_209': {}, 'E_196': {}, 'E_123': {}, 'E_124...",3
40,Acute rhinosinusitis,Rhinosinusite aigue,Acute rhinosinusitis,j01,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_209': {}, 'E_121': {}, 'E_79': {}, 'E_125'...",4
41,Chronic rhinosinusitis,Rhinosinusite chronique,Chronic rhinosinusitis,j32,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_116': {}, 'E_121': {}, 'E_79': {}, 'E_125'...",5
42,Bronchiolitis,Bronchiolite,Bronchiolitis,j21,"{'E_201': {}, 'E_66': {}, 'E_32': {}, 'E_181':...","{'E_209': {}, 'E_142': {}, 'E_48': {}, 'E_195'...",3
43,Pulmonary neoplasm,néoplasie pulmonaire,Pulmonary neoplasm,c34,"{'E_55': {}, 'E_53': {}, 'E_45': {}, 'E_162': ...","{'E_191': {}, 'E_79': {}, 'E_224': {}, 'E_222'...",3
44,Possible NSTEMI / STEMI,Possible NSTEMI / STEMI,Possible NSTEMI / STEMI,I21,"{'E_161': {}, 'E_55': {}, 'E_53': {}, 'E_57': ...","{'E_105': {}, 'E_108': {}, 'E_191': {}, 'E_79'...",1
45,Sarcoidosis,Sarcoïdose,Sarcoidosis,d86,"{'E_133': {}, 'E_129': {}, 'E_130': {}, 'E_134...","{'E_70': {}, 'E_198': {}, 'E_204': {}}",4
46,Pancreatic neoplasm,Néoplasie du pancréas,Pancreatic neoplasm,c25,"{'E_55': {}, 'E_53': {}, 'E_57': {}, 'E_54': {...","{'E_69': {}, 'E_79': {}, 'E_70': {}, 'E_223': ...",3
47,Acute pulmonary edema,OAP/Surcharge pulmonaire,Acute pulmonary edema,J81.0,"{'E_218': {}, 'E_55': {}, 'E_53': {}, 'E_57': ...","{'E_105': {}, 'E_106': {}, 'E_5': {}, 'E_104':...",1
48,Pericarditis,Péricardite,Pericarditis,I30,"{'E_220': {}, 'E_217': {}, 'E_55': {}, 'E_53':...","{'E_0': {}, 'E_3': {}, 'E_204': {}}",4

## converting release_evidences.json to dataframe

In [6]:
with open("release_evidences.json") as jf:
    data = json.load(jf)

In [7]:
# keys present in the json data
keys = list(data.keys())
print('Dictionary Keys (all evidences): ',keys)
print()
print('Total Number of evidences: ',len(keys))
print()
print('Keys for an evidence: ', data[keys[0]].keys())

Dictionary Keys (all evidences):  ['E_91', 'E_55', 'E_53', 'E_57', 'E_54', 'E_59', 'E_56', 'E_58', 'E_159', 'E_133', 'E_129', 'E_130', 'E_134', 'E_132', 'E_136', 'E_135', 'E_131', 'E_154', 'E_155', 'E_210', 'E_140', 'E_51', 'E_75', 'E_89', 'E_114', 'E_82', 'E_148', 'E_94', 'E_220', 'E_161', 'E_179', 'E_162', 'E_173', 'E_33', 'E_218', 'E_93', 'E_66', 'E_163', 'E_30', 'E_127', 'E_181', 'E_88', 'E_43', 'E_156', 'E_144', 'E_216', 'E_201', 'E_217', 'E_215', 'E_64', 'E_96', 'E_16', 'E_50', 'E_97', 'E_9', 'E_76', 'E_102', 'E_65', 'E_74', 'E_205', 'E_63', 'E_128', 'E_190', 'E_39', 'E_212', 'E_206', 'E_52', 'E_203', 'E_38', 'E_172', 'E_84', 'E_90', 'E_211', 'E_166', 'E_112', 'E_178', 'E_152', 'E_151', 'E_45', 'E_194', 'E_83', 'E_157', 'E_176', 'E_42', 'E_214', 'E_150', 'E_32', 'E_221', 'E_202', 'E_219', 'E_196', 'E_170', 'E_77', 'E_13', 'E_14', 'E_169', 'E_177', 'E_175', 'E_174', 'E_145', 'E_92', 'E_192', 'E_188', 'E_164', 'E_193', 'E_168', 'E_180', 'E_67', 'E_78', 'E_146', 'E_171', 'E_111', 'E_182', 'E_103', 'E_23', 'E_105', 'E_108', 'E_104', 'E_79', 'E_71', 'E_41', 'E_100', 'E_69', 'E_167', 'E_115', 'E_70', 'E_10', 'E_165', 'E_8', 'E_25', 'E_184', 'E_185', 'E_99', 'E_107', 'E_226', 'E_62', 'E_49', 'E_95', 'E_204', 'E_37', 'E_153', 'E_124', 'E_98', 'E_116', 'E_48', 'E_2', 'E_227', 'E_61', 'E_47', 'E_27', 'E_143', 'E_191', 'E_208', 'E_126', 'E_189', 'E_7', 'E_24', 'E_26', 'E_113', 'E_160', 'E_28', 'E_20', 'E_80', 'E_40', 'E_0', 'E_1', 'E_34', 'E_209', 'E_139', 'E_19', 'E_31', 'E_22', 'E_60', 'E_35', 'E_213', 'E_12', 'E_44', 'E_4', 'E_81', 'E_109', 'E_110', 'E_17', 'E_18', 'E_118', 'E_123', 'E_207', 'E_86', 'E_87', 'E_141', 'E_11', 'E_186', 'E_106', 'E_158', 'E_187', 'E_6', 'E_125', 'E_21', 'E_222', 'E_15', 'E_147', 'E_137', 'E_149', 'E_197', 'E_3', 'E_29', 'E_225', 'E_73', 'E_138', 'E_101', 'E_46', 'E_119', 'E_72', 'E_198', 'E_200', 'E_199', 'E_121', 'E_120', 'E_142', 'E_195', 'E_183', 'E_224', 'E_223', 'E_5']

Total Number of evidences:  223

Keys for an evidence:  dict_keys(['name', 'code_question', 'question_fr', 'question_en', 'is_antecedent', 'default_value', 'value_meaning', 'possible-values', 'data_type'])

In [8]:
df = pd.DataFrame.from_dict(data, orient='index')
df = df.reset_index(drop=True)

In [9]:
# save dataframe as csv
df.to_csv('release_evidences.csv', index=False)

,name,code_question,question_fr,question_en,is_antecedent,default_value,value_meaning,possible-values,data_type
0,E_91,E_91,Avez-vous objectivé ou ressenti de la fièvre?,Do you have a fever (either felt or measured w...,False,0,{},[],B
1,E_55,E_53,Avez-vous de la douleur quelque part?,Do you feel pain somewhere?,False,V_123,"{'V_123': {'fr': 'nulle part', 'en': 'nowhere'...","[V_123, V_14, V_15, V_16, V_17, V_18, V_19, V_...",M
2,E_53,E_53,Avez-vous de la douleur à quelque part en lien...,"Do you have pain somewhere, related to your re...",False,0,{},[],B
3,E_57,E_53,Est-ce que la douleur se propage vers un autre...,Does the pain radiate to another location?,False,V_123,"{'V_123': {'fr': 'nulle part', 'en': 'nowhere'...","[V_123, V_14, V_15, V_16, V_17, V_18, V_19, V_...",M
4,E_54,E_53,Caractérisez votre douleur:,Characterize your pain:,False,V_11,"{'V_11': {'fr': 'NA', 'en': 'NA'}, 'V_71': {'f...","[V_11, V_71, V_112, V_154, V_161, V_179, V_180...",M
...,...,...,...,...,...,...,...,...,...
218,E_195,E_195,Habitez-vous en banlieue?,Do you live in the suburbs?,True,0,{},[],B
219,E_183,E_183,Habitez-vous en à la campagne?,Do you live in a rural area?,True,0,{},[],B
220,E_224,E_224,Avez-vous des membres de votre famille ayant e...,Do you have family members who have had lung c...,True,0,{},[],B
221,E_223,E_223,Avez-vous des membre de votre famille proche q...,Are there members of your family who have been...,True,0,{},[],B
222,E_5,E_5,Avez-vous déjà fait de l’eau sur les poumons?,Have you ever had fluid in your lungs?,True,0,{},[],B

### separating unique values from the 'value meanings' column (used for multiple choice questions) from 'release_evidences'

In [10]:
value_list = []
for value in df['value_meaning']:
    # check if the cell has values
    if value:
        value_list.append(value)

In [11]:
col_names = ['index', 'fr', 'en']

values_df = pd.DataFrame(columns = col_names)

for value_dict in value_list:
    temp_df = pd.DataFrame.from_dict(value_dict, orient='index')
    temp_df = temp_df.reset_index()
    
    values_df = pd.concat([values_df, temp_df], ignore_index=True)

In [12]:
len(values_df)

698

In [13]:
# remove duplicate instances
unique_values_df = values_df.drop_duplicates(subset='index', keep='first')
len(unique_values_df)

199

In [14]:
unique_values_df.reset_index(drop=True, inplace=True)

In [15]:
unique_values_df.to_csv('Values_meanings.csv', index=False)

     index                fr               en
0    V_123        nulle part          nowhere
1     V_14   aile iliaque(D)    iliac wing(R)
2     V_15   aile iliaque(G)    iliac wing(L)
3     V_16           aine(D)         groin(R)
4     V_17           aine(G)         groin(L)
..     ...               ...              ...
194    V_6              Asie             Asia
195    V_7  Asie Sud-Sud-Est  South East Asia
196    V_8          Caraibes         Caraibes
197    V_9            Europe           Europe
198   V_13          Océeanie          Oceania

[199 rows x 3 columns]